Use enums instead of static const.
At least some versions of GCC 4.8 are complaining about
undefined reference to `protozero::pbf_writer::reserve_bytes'.